# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mycor <- function(MAT_CORR, cf, t, cor, nug, alpha, nu) {
    .Call(`_myCor_mycor`, MAT_CORR, cf, t, cor, nug, alpha, nu)
}

mycor2 <- function(XX, n, n0, cf, t, cor, nug, alpha, nu) {
    .Call(`_myCor_mycor2`, XX, n, n0, cf, t, cor, nug, alpha, nu)
}

mycor3 <- function(MAT_CORR, MAT_CORR2, cf, t, cor, nug, alpha, nu) {
    .Call(`_myCor_mycor3`, MAT_CORR, MAT_CORR2, cf, t, cor, nug, alpha, nu)
}

rcpparma_hello_world <- function() {
    .Call(`_myCor_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_myCor_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_myCor_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_myCor_rcpparma_bothproducts`, x)
}

